version: '3.8'
services:
  database:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - backend
  cache:
    image: 'redis:latest'
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
    ports:
      - 6379:6379
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    name: infrastructure
